### ISSUE TITLE
Can't commit a message starting with GitHub identifier (#)

### ISSUE THREAD

**Issue by basilevs** [eclipse-egit/egit#15]
### Version

6.8.0

### Operating System

MacOS

### Eclipse version

2024-03

### Bug description

# Test steps
Change any file
Add the file to Staged changes
Enter commit message in Staging view:
```
#882 Style fixes
```
Hit commit button

### Actual behavior

A modal dialog "No message" with a message: "You must enter a commit message"
<img width="743" alt="Screenshot 2024-01-23 at 00 06 16" src="https://github.com/eclipse-egit/egit/assets/650857/4ffa75c9-407e-4664-87ca-f081fdb41784">

### Expected behavior

Commit succeeds

### Other information

While pretty-printing comment in commit message might be useful, use of popular issue reference format is much more important.

**Comment by msohn** [comment]
That's configurable using the option [`commit.cleanup`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-commitcleanup). It you set it to `whitespace` lines starting with `#` aren't removed.

**Comment by basilevs** [comment]
Thanks
