### ISSUE TITLE
one picture missing in UserGuide@wiki

### ISSUE THREAD

**Issue by Pfiffikus** [eclipse-egit/egit#17]
### Version

current

### Operating System

Linux/Unix, MacOS, Windows

### Eclipse version

current

### Bug description

Last picture, e.g. File:Egit-3.4-merge-options.png (just above https://github.com/eclipse-egit/egit/wiki/User-Guide#possible-merge-results), need to be included correctly.

### Actual behavior

just tag is shown

### Expected behavior

picture is visible

**Comment by tomaswolf** [comment]
Link was broken in the markdown. Fixed.
