### ISSUE TITLE
Does not filter content assist for previous message on files shown

### ISSUE THREAD

**Issue by Kiiv** [eclipse-egit/egit#26]
### Description

Egit support content assist in the commit message field ("Git staging" view).
Unfortunately, previous messages are associated with the files for which they were initially written.

It should be great to have access to last (15 ?) previous messages independently of the files. History is great to find quickly the ticket number on which we are working and we need to push other files for.

### Motivation

I'm working on ticket JIRA-321.
I made a commit on fileA with the message "JIRA-321 : changes on fileA".
I need to also change fileB after some considerations. I try to make a commit on fileB and want my message to be "JIRA-321 : changes on fileB". 
I would be able to reuse my previous message containing the ticket number because my memory is not so good anymore. It would be great to select previous message from a list and be able to edit its content before commiting.

### Additional context

Subversive and Subclipse (Eclipse plugin for Subversion) support that and I miss it :)

**Comment by Bananeweizen** [comment]
You have the last 10 messages via Ctrl+Space. For everything more complex, please use the Mylyn plugin. It's exactly made for working in the context of some task, and can populate your git commit message (and other things) based on the task.
