### ISSUE TITLE
https://download.eclipse.org/egit/updates/ points to 6.8 content not 6.9

### ISSUE THREAD

**Issue by akurtakov** [eclipse-egit/egit#27]
### Version

6.9

### Operating System

Linux/Unix

### Bug description

If one uses https://download.eclipse.org/egit/updates/ Egit 6.8 is still served despite having https://download.eclipse.org/egit/updates-6.9/ . 

### Actual behavior

Serves EGit 6.8 repo.

### Expected behavior

Should serve Egit 6.9 repo.

**Comment by msohn** [comment]
Thanks for the heads-up. I missed to run the publish job copying the new release to https://download.eclipse.org/egit/updates. I did that now and the new content reached this update site:
https://download.eclipse.org/justj/?file=egit/updates
