### ISSUE TITLE
EGit's stale dependencies

### ISSUE THREAD

**Issue by merks** [eclipse-egit/egit#3]
EGit has a growing number of stale dependencies:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/egit/REPORT.md

It's also the last project relying on Jetty 10.x where all the others have migrated to Jetty 12.x.

**Comment by merks** [comment]
Oh, this could be "my bad" because I didn't notice there is this now:

https://git.eclipse.org/c/egit/egit.git/plain/org.eclipse.egit.target/egit-4.30.target

I will reassess...

**Comment by merks** [comment]
No the same comment pretty applies to the newer target which is analyzed by the updated reported.

**Comment by msohn** [comment]
I merged a first round of updates today
https://git.eclipse.org/r/c/egit/egit/+/205474

**Comment by merks** [comment]
If there are delays with your contribution just let me know so I can delay tomorrow morning. It’s not a problem.

**Comment by msohn** [comment]
egit milestone build is currently running, will contribute it in about 15min

**Comment by msohn** [comment]
Will catch up with dependency updates soon. Spent some time on preparing move of jgit and egit to eclipse.gerrithub.io
instead of working on the content ;-(
Will switch over to gerrithub soon, see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3137

**Comment by msohn** [comment]
I contributed the new milestone

**Comment by merks** [comment]
I will regenerate the reports tomorrow.

**Comment by msohn** [comment]
- https://git.eclipse.org/r/c/egit/egit/+/205474
- https://git.eclipse.org/r/c/egit/egit/+/205482

**Comment by msohn** [comment]
update bouncycastle to 1.77 https://git.eclipse.org/r/c/egit/egit/+/205484

**Comment by msohn** [comment]
Completed all the minor updates.
In 6.8 we may also consider the major update of slf4j to 2.x, will wait with major update of servlet API and Jetty until the next release. Jetty is only used in JGit (GitServlet and HTTP tests).

**Comment by merks** [comment]
The jetty thing is understand but it's unfortunate because it drags in a lot of duplicates:

![image](https://github.com/eclipse-egit/egit/assets/208716/b6a14d46-42dc-48c4-9909-7c90ca1b722f)

But I see it's only for this bundle/feature:

![image](https://github.com/eclipse-egit/egit/assets/208716/7d6cd929-88c7-463e-97c5-649f27993901)

which doesn't end up in packages:

![image](https://github.com/eclipse-egit/egit/assets/208716/a71c9d30-3614-4895-bcd7-ebc1e8ff1d08)

**Comment by msohn** [comment]
Yes, but updating to servlet 6 is a breaking change for those who subclass [GitServlet](https://github.com/eclipse-jgit/jgit/blob/master/org.eclipse.jgit.http.server/src/org/eclipse/jgit/http/server/GitServlet.java) hence we refrain from doing this in a minor release. And Jetty 12 requires raising the Java version to 17.
I guess we will do both in the next release and call it 7.0.

**Comment by merks** [comment]
I fully understand!  I'm not trying to apply pressure.   This is justifiable, does not have broad ranging impact, and does not cause problems.
