### ISSUE TITLE
Keep target platform dependencies up-to-date

### ISSUE THREAD

**Issue by merks** [eclipse-egit/egit#34]
### Description

Orbit generates a report for EGit's target platform:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/egit/REPORT.md

You can literally copy and paste this updated version:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/egit/updated.target

to replace this version:

https://raw.githubusercontent.com/eclipse-egit/egit/master/org.eclipse.egit.target/egit-4.32.target

The reports are generally regenerated 5+ times per week.

---

These updates are currently available:

## Minor Updates
 - [commons-codec](https://repo1.maven.org/maven2/commons-codec/)
    - [commons-codec](https://repo1.maven.org/maven2/commons-codec/commons-codec/) **[1.16.0](https://repo1.maven.org/maven2/commons-codec/commons-codec/1.16.0)** < [1.17.0](https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/)
 - [commons-io](https://repo1.maven.org/maven2/commons-io/)
    - [commons-io](https://repo1.maven.org/maven2/commons-io/commons-io/) **[2.15.0](https://repo1.maven.org/maven2/commons-io/commons-io/2.15.0)** < [2.16.1](https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/)
    - [commons-io](https://repo1.maven.org/maven2/commons-io/commons-io/) **[2.15.1](https://repo1.maven.org/maven2/commons-io/commons-io/2.15.1)** < [2.16.1](https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/)
 - [org.eclipse.jetty](https://repo1.maven.org/maven2/org/eclipse/jetty/)
    - [jetty-http](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/10.0.21/)
    - [jetty-io](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/10.0.21/)
    - [jetty-security](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/10.0.21/)
    - [jetty-server](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/10.0.21/)
    - [jetty-servlet](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/10.0.21/)
    - [jetty-util](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/10.0.21/)
    - [jetty-util-ajax](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/) **[10.0.20](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.20)** < [10.0.21](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util-ajax/10.0.21/)

### Motivation

It's best to use the latest dependencies.

**Comment by merks** [comment]
I've been looking closely at how EGit/JGit define the target platforms using TPD and am looking at updating Orbit's maven dependency analyzer to analyze/updates the *.tpd file instead of the generated *.target.

I get the impression that perhaps these "duplicates" were added by mistake:

https://github.com/eclipse-egit/egit/blob/91ea5b1b809340307e720b1611f742f141c91ea5/org.eclipse.egit.target/maven/dependencies.tpd#L19-L28

Is that correct, i.e., are these duplicates pointless?

Also, after the Orbit generator updates the dependencies.tpd and I then regenerate a *.target with TPD, there are a lot of whitespace difference.  I'm wondering how exactly the *.target was produced in the past such that it contains tab characters?

![image](https://github.com/eclipse-egit/egit/assets/208716/de072e20-164e-478f-b2d5-b91fd7afc696)

**Comment by merks** [comment]
FYI, the report generator now generates an updated *.tpd:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/egit/updated.tpd

**Comment by msohn** [comment]
This change series has the updates for EGit target platform:
https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1194983

https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1194980 also removes the duplicate version for commons-io

**Comment by msohn** [comment]
The .target files are generated in Eclipse IDE using the "Target Platform Definition DSL and Generator" plugin's action "Create Target Definition File".

**Comment by msohn** [comment]
submitted the updates

**Comment by Bananeweizen** [comment]
> Also, after the Orbit generator updates the dependencies.tpd and I then regenerate a *.target with TPD, there are a lot of whitespace difference. I'm wondering how exactly the *.target was produced in the past such that it contains tab characters?

The TPD generator generated tab characters until one year ago, when I fixed that in https://github.com/eclipse-cbi/targetplatform-dsl/commit/26559a67739bfe323a8fa39f495ce9f17c0d8cb1. So the files have not been re-generated at all or with a more recent version of the TPD plugin since then. Not sure if someone needs to run Help>Perform Setup tasks maybe to force a local update.

**Comment by merks** [comment]
@Bananeweizen 

Yes, I had a feeling older tooling was involved.  The current output with just spaces is nicer...

**Comment by msohn** [comment]
caught me, will update the TPD plugin
