### ISSUE TITLE
Provide Support for gpgsm (X.509) Commit Signing

### ISSUE THREAD

**Issue by ajh-** [eclipse-egit/egit#36]
### Description

The ability to use gpgsm as an alternative gpg executable for signing commits. Inside (and outside) the Eclipse terminal, I am able to sign commits using the gpgsm executable and a smart card. However, when trying to use the egit plugin, it throws an error about an invalid option "--locate-keys" which exists in gpg but not in gpgsm.

### Motivation

This would allow users to use smart cards (and other potential X.509 solutions) to sign their git commits using the egit plugin.

### Alternatives considered

Open a terminal within (or outside) Eclipse and sign commits using gpgsm that way.

**Comment by tomaswolf** [comment]
JGit is currently adding support for this. We may consider this for the September release.

**Comment by tomaswolf** [comment]
We've merged [Gerrit change 1199995](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1199995), which implements this if an external GPG is used (see the configuration under "Version Control (Team)&rarr;Git&rarr;Committing").

The change should be available in [EGit nightly](https://download.eclipse.org/egit/updates-nightly). (Note: requires Java 17.)

@ajh- : would be great if you could test this. I don't have a smart card or other hardware to test with. Internally, the code first looks whether it can find a signing certificate for which there is a secret key using `gpgsm --list-secret-keys`. That works fine for normal certificates, but I don't know if it also works for certificates from a smart card, where the secret key would be held on the card. If it does not work, please give me the full output of `gpgsm --list-keys` for that certificate/key.

**Comment by ajh-** [comment]
@tomaswolf Just tested the nightly build and it worked with no issues. Thanks again!

**Comment by tomaswolf** [comment]
Cool; thank you for double checking!
