### ISSUE TITLE
Integrate syntax highlighting in egit's compare editor

### ISSUE THREAD

**Issue by systemoperator** [eclipse-egit/egit#41]
### Description

It would be great if there was syntax highlighting integrated in egit's compare editor (diff viewer) for various programming languages.

Eclipse recently announced a new, versatile syntax highlighting functionality for more than 60 languages with TextMate and it also works in the compare editor, which should be the way to go:

- https://www.heise.de/news/IDE-Eclipse-2024-06-Java-22-und-Syntax-Highlighting-fuer-fast-alles-9759399.html
- https://projects.eclipse.org/projects/technology.tm4e
- https://marketplace.eclipse.org/content/extra-syntax-highlighting-plugin
- https://eclipse.dev/eclipse/news/4.7/platform.php
- https://github.com/eclipse-cdt/cdt-lsp
- https://github.com/eclipse/lsp4e
- https://github.com/eclipse/tm4e

### Motivation

Other diff-viewers and git UIs offer that. It makes the differences easier to read and merge.

**Comment by iloveeclipse** [comment]
Actually that is already done in 4.32, see https://eclipse.dev/eclipse/news/4.32/platform.php#generic_editor_in_diff

All what you need is Textmate + language pack installed in 4.32 SDK. The rest is working out of the box for all types supported by Textmate.
