### ISSUE TITLE
default behaviour for FileDiff double click changed

### ISSUE THREAD

**Issue by Madjosz** [eclipse-egit/egit#43]
### Version

6.10.0.202406032230-r

### Operating System

Windows

### Eclipse version

2024-06

### Bug description

When in History view (GitHistoryPage) having selected a commit and then double clicking a changed file in the file menu bottom left up until 6.9.0 the diff viewer opened "Compare with previous version". This changed in 6.10.0 to "Open this version" instead which feels uncomfortable for me since I use this function mainly to check for incoming changes.

### Actual behavior

"Open this version" of the selected file for the selected commit

### Expected behavior

"Compare with previous version "of the selected file for the selected commit

### Other information

The change was likely introduced in one of the commits 4ec86b422f3d9a826e9db67bdde8baede0021f26, 6563260bde2bfe6e2eba2051174ddf287f0ab071, 783a5457a64cf735a6135e8f2e779699c306cc67, 0e458fca7694e065b4ae74fb2e228c45137f1f74 by @tomaswolf

**Comment by tomaswolf** [comment]
* I suppose you mean "bottom right".
* Does not occur for me.

Double check that "Compare Mode" is enabled. (View toolbar, between the "Filter" button and the branches buttons.)

**Comment by Madjosz** [comment]
Oh, you are right, I wasn't aware of this feature and must have deactivated it by accident.

Sorry, I'll close this issue.
