### ISSUE TITLE
explore alternatives to jgit

### ISSUE THREAD

**Issue by janesser** [eclipse-egit/egit#47]
### Description

egit should have different backends like jgit - as it is implemented now and alternatives.

thought 1: libgit2 via jni
git-scm team is having main priority on git-cli, as a consequence fixes are first applied there before eventually being ported to libgit2

thought 2: cli wrapper
running java subprocesses has some challenges that need to be coped with. think of linux process fork and pagetables of possibly bigger memheaps

### Motivation

jgit alternatives would be selectable when situation requires.

### Alternatives considered

approaches differ where to apply abstraction layer:
- should jgit have backend ? classy package layout with jgit.api
- should egit have backends ? classy package layout with egit.internal
- can the exposed api be maintained without jgit ? to be verified
- can the junit suite be sustained ? to be verified
- feature parity throughout providers may differ ?

https://github.com/kawansoft/SympleGit-Java

### Additional context

by this follow the path established on sonar, jenkins and others where git is frequently used.

for completeness: https://github.com/JetBrains/intellij-community/blob/master/plugins/git4idea/src/git4idea/commands/GitImpl.java

coarchi2 is attempting to circumvent the egit situation by a single file scheme

my particular use-case resides on a partially optimized citrix-platform, where around 10 people coop over git

**Comment by msohn** [comment]
We don't consider to add support for other git implementations than JGit.
The project scope (https://projects.eclipse.org/projects/technology.egit) is: "The EGit project is implementing Eclipse tooling for the JGit Java implementation of Git."
