### ISSUE TITLE
Quick Diff does not work in EGit 7.0.0

### ISSUE THREAD

**Issue by estepper** [eclipse-egit/egit#50]
### Version

7.0.0

### Operating System

Windows

### Eclipse version

2024-09

### Bug description

I'm used to see Quick Diff annotations in my left and right editor rulers:

![image](https://github.com/user-attachments/assets/6f9bd703-46f3-4c5c-ab24-fa6b15abab3b)

See example below...

### Actual behavior

There are no more Git revision Quick Diff annotations anymore with EGit 7.0.0. Even though "A Git Revision" is selected (see above) it seems to display Diff info of the "Version on Disk" provider. Not sure if that's a problem in the Platform?

### Expected behavior

This is how it looks/behaves with EGit 6.10.0:

![image](https://github.com/user-attachments/assets/eb40cfbd-4ab2-45c8-b6d8-09d6c6869cce)

**Comment by tomaswolf** [comment]
There have been no changes in EGit in that respect. I suspect this might be related to https://github.com/eclipse-platform/eclipse.platform/issues/1489 ?

**Comment by iloveeclipse** [comment]
> There have been no changes in EGit in that respect. I suspect this might be related to [eclipse-platform/eclipse.platform#1489](https://github.com/eclipse-platform/eclipse.platform/issues/1489)

That's completely different story.

**Comment by estepper** [comment]
Can someone reproduce the problem?

**Comment by humphreygao** [comment]
Update to latest version.

**Comment by msohn** [comment]
I tried and installed 2024-09 M2 Eclipse IDE for Committers, imported jgit, configured quick diff to use git and did a one line test change, and quick diff works:

<img width="331" alt="Screenshot 2024-08-15 at 12 54 22" src="https://github.com/user-attachments/assets/554e7018-396c-4bd1-8e40-1a6f273197d2">

**Comment by estepper** [comment]
And you're sure that this is not the "Version on Disk" provider?

I just updated my IDE (with nothing new coming in) and still have the problem. This is installed:

![image](https://github.com/user-attachments/assets/b1b57cff-28d7-4b89-9674-5860321524e5)

**Comment by estepper** [comment]
I can confirm that in my IDE the "A Git Revision" provider behaves exactly like the "Version on Disk" provider. Perhaps that gives a clue?

**Comment by estepper** [comment]
And I always reopen the editor after changing the Quick Diff provider.

**Comment by iloveeclipse** [comment]
@estepper :  could you please try with a new workspace **without** Oomph? I guess your settings might be changed in some way and remembered by Oomph.

**Comment by estepper** [comment]
I found the cause of the problem. None of my IProjects were "connected" with EGit anymore. No idea how or when that happened. But by removing all projects from my workspace and re-importing them with EGit also the Quick Diff worked again.
