### ISSUE TITLE
Should consider (and remove ? )  the github.com/eclipse-git organization... which is confusing

### ISSUE THREAD

**Issue by opcoach** [eclipse-egit/egit#53]
### Description

I found this organization on GitHub :  https://github.com/eclipse-git

I think this is confusing... it was created a long time ago and contains no repository... 

### Motivation

This is confusing.

**Comment by Bananeweizen** [comment]
While I agree to this being confusing, I'm not sure whether that's sufficient to report this account for abuse or similar. People come up with all kinds of names, so I would not immediately assume this to be some kind of typosquatting.

**Comment by msohn** [comment]
I raised https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4952 on the Eclipse help desk to get guidance from Eclipse Foundation how to handle this.

**Comment by msohn** [comment]
According to Wayne Beaton there is nothing we can do about this and he recommends we ignore this organization.
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4952
