### ISSUE TITLE
Please use latest Jetty dependency

### ISSUE THREAD

**Issue by merks** [eclipse-egit/egit#60]
### Description

Currently you're using 12.0.14 but 12.0.15 is available.  Look here:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/egit/REPORT.md

### Motivation

RAP is using the latest version so EGit using the older version results in duplicates SimRel:

![image](https://github.com/user-attachments/assets/b2b09d25-a7fd-4123-b934-947a992a26ae)

**Comment by msohn** [comment]
pushed Jetty update to 12.0.15 for review:
EGit: https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1203911
JGit: https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1203910

**Comment by msohn** [comment]
changes were submitted
