### ISSUE TITLE
Enhanced support of Git Tags in Team Projects Sets

### ISSUE THREAD

**Issue by DirkBaumannDXC** [eclipse-egit/egit#61]
### Description

Hi,

According to the contribution guidelines I've created a Gerrit request on April 2023 for this issue (see: https://gerrithub.io/c/eclipse-egit/egit/+/201326/1). The issue is marked as "Verified", but there seems to be no further reaction. Is there something missing or I can do for the next steps for contribution or do I just have to wait?

Best regards,
 Dirk Baumann

### Motivation

see Gerrit: https://gerrithub.io/c/eclipse-egit/egit/+/201326/1

**Comment by tomaswolf** [comment]
Thanks and sorry for having missed this. The change is merged now.
