### ISSUE TITLE
Strange behavior when inputing text in create branch dialog

### ISSUE THREAD

**Issue by zwxue** [eclipse-egit/egit#64]
### Version

6.10.0

### Operating System

MacOS

### Eclipse version

2024-06

### Bug description

1. enable input source 'Pinyin-Simplified' in macOS which when you input any word, it will pop-up a small dialog for you to choose
2. right-click a git repository in Eclipse and click switch to new branch
3. in the pop-up dialog, switch to 'Pinyin-Simplified', input 'zw', it will output immediately 'z_w', if input 'mas', it will output 'mama_s'
there's no such issue in any other dialog or editors

### Actual behavior

looks like EGit is monitoring the keyboard input too early in this case, maybe some listener has a conflict with the listener of Mac input source while they were activated at the same time

### Expected behavior

if a special input source with a dialog is activated, EGit should trigger the listener only when input source returns the text from its dialog

**Comment by Bananeweizen** [comment]
We use a verifylistener to replace invalid characters in branch names: https://github.com/eclipse-egit/egit/blob/0ed40cb84dbdd41c19bdf90c03bd24d2ad4496e1/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/components/BranchNameNormalizer.java#L96-L97
Such verifylisteners are called very early. We could probably move that code into the modifylistener instead, which is rather late (such that the pinyin conversion might come first). However, I'm not sure how such IME conversion tooling works, and I surely can't reproduce, as I'm not on MacOS.

**Comment by zwxue** [comment]
Thank you for pointing out the code location, I did a simple test on my side, it can be easily reproduced by a Text control with a VerifyListener, so it should be platform issue for SWT but not EGit
