### ISSUE TITLE
Defect popup menu in Git Repositories part

### ISSUE THREAD

**Issue by col-panic** [eclipse-egit/egit#65]
### Version

7.1.0.202411191359-rc1

### Operating System

MacOS

### Eclipse version

4.34.0 RC1

### Bug description

This is the way the popu menu in Eclipse looks like since the last update

![grafik](https://github.com/user-attachments/assets/d58cfc40-be31-42f3-b889-a917ea90e44d)

### Actual behavior

I updated to RC1

### Expected behavior

Like this

![grafik](https://github.com/user-attachments/assets/e46c927a-1ee6-4411-ad68-5fb3c71979d9)

**Comment by col-panic** [comment]
Somehow I'm not sure about this - if this is legit, the popup menu is far too long. Can't really see about where all the options are coming from?!

**Comment by msohn** [comment]
I couldn't reproduce this, I freshly downloaded and installed
```
Eclipse IDE for Eclipse Committers (includes Incubating components)
Version: 2024-12 RC1 (4.34.0 RC1)
Build id: 20241121-0709
```
With that the menu in the repositories view looks like expected and doesn't show this long list of actions.

**Comment by col-panic** [comment]
After starting with `-clearPersistedState` the problem has gone. Something seemed to have messed up the
workbench.xmi 🤷

**Comment by Bananeweizen** [comment]
I'm somewhat certain that I have seen a similar issue in the past (with all the menu items contained several times), but I can't find it. I also don't remember a solution for that other one.
