### ISSUE TITLE
Odd names of stash in Git repositories Name

### ISSUE THREAD

**Issue by jukzi** [eclipse-egit/egit#67]
### Version

latest

### Operating System

Windows

### Eclipse version

latest

### Bug description

![image](https://github.com/user-attachments/assets/3d018e60-47cb-4405-898e-9824bd5035fe)

### Actual behavior

The name "stash@{0}" feels wrong

### Expected behavior

i would have expected that the name i gave to the squash would show up as item, but it's only on the right most

**Comment by msohn** [comment]
AFAICS the first part is the usual enumeration of stashes in the format you get from `git stash list`, 
the next one is the commitId and then comes the message you entered ?

See https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-listltlog-optionsgt

**Comment by jukzi** [comment]
yes, the last thing is what i entered and i expected that to be the node name. i do not see a value to see "stash@{0}" in a ui

**Comment by tomaswolf** [comment]
Having the stack ref or at least the number in the label is useful if you want to do something with it on the git command line.

I suggest we close this as "won't fix".

**Comment by jukzi** [comment]
When i stash something within eclipse as "xyz" and i can hardly find "xyz" in eclipse it is not useful.
Maybe just change the order so that the name "xyz" is the item name and the "stash@{0}" is shown as annotation in the back?

**Comment by msohn** [comment]
Here is a change implementing what you proposed: https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1205641

With that it looks like this
<img width="661" alt="Screenshot 2024-12-12 at 16 36 43" src="https://github.com/user-attachments/assets/435147e0-78ca-4da9-83fa-047badada95a" />

**Comment by jukzi** [comment]
looks great, thanks

**Comment by msohn** [comment]
merged as 1bf3fd462ecce506121fd5119a0f9895f9bc880f
